language: ruby
rvm:
  - 2.4
before_install:
  - nvm install 6
  - npm install gulp-cli -g
  - npm install git+https://git@github.com/gulpjs/gulp.git#4.0 --save-dev
install:
  bundle install
cache:
  bundler: true
  directories:
    - node_modules
deploy:
  provider: master
  skip-cleanup: true
  github-token: $a2f51fb5d47d7a04e5e0b4b83c229910007aea6b  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
after_success:
  - eval "$(ssh-agent)"
  - chmod 600 ./deploy.secret.key
  - ssh-add ./deploy.secret.key
  - cd deploy
  - git checkout -B master
  - git add -A
  - git commit --allow-empty -m "$TRAVIS_COMMIT_MSG"
  - echo "Pushing changes"
  - git push git@github.com:donaldboulton/bibwoe.git master